{*On étend le layout*}
{extends file="layout/layout.tpl"}
{*On affiche le contenu de la page*}
{block name="content"}
    <h1 class="text-uppercase text-underline text-center my-5">General Data Protection regulation</h1>
    <section class="card border-purple mt-4 text-center p-2">
        <p>Lorem ipsum dolor sit amet. Quo asperiores ipsamEt tempore quo Quis commodi est unde illum qui enim similique. Ut architecto totamEos galisum quo error voluptas id voluptatem sunt et quibusdam minima. 33 provident neque <strong>Ut iste et illum fugit ex saepe doloribus</strong> a ducimus consectetur. Sed voluptatem quasi et voluptatem voluptasqui voluptatibus. Est nostrum consequuntur et obcaecati assumendaEos accusantium cum eius voluptatem est sunt deleniti ab architecto omnis? Eos dolor doloremque <em>Ut sint ut inventore perferendis</em>. Quo ducimus magnamEst beatae id illum nihil At totam unde hic soluta ipsum hic dolor quibusdam. </p>
        <p>Sed voluptas voluptate At ducimus suntQui quos. Et animi adipisci <strong>Quo unde ut omnis praesentium sed velit suscipit</strong> aut galisum quae ut molestiae quibusdam. Ad quaerat consequaturEt omnis ad iste culpa ut vitae enim et dolor quia. Et iusto mollitiaQui voluptatum hic nostrum sint ut illo omnis cum obcaecati praesentium. At adipisci autemUt nihil cum voluptas harum qui omnis autem et perferendis distinctio. </p>
        <p>Qui explicabo voluptatem in perspiciatis doloresAt libero et animi perferendis ut Quis corrupti nam placeat quos et cupiditate illum. Ad nisi adipisci eos reprehenderit suscipitsit autem eos voluptatem repellat et pariatur accusamus? Ea esse saepe in earum voluptasaut similique et quia soluta et saepe optio. Ut voluptatem repellendus quo mollitia sintet animi vel pariatur sint? Et fugit voluptasAut nostrum ea quasi doloribus in debitis culpa sit quia voluptas sit delectus voluptas. Et voluptas voluptas aut voluptatem praesentiumAut omnis aut similique sunt qui officiis galisum. Sed magnam quos sit sunt doloresIn itaque. Non quos inciduntEx facilis et magni ratione et voluptas omnis cum corrupti ipsa est obcaecati quod eum rerum pariatur. Est commodi delectusRem nesciunt et laudantium impedit in tempora accusantium cum quia consequuntur 33 dolore nemo. </p>
        <p>Et saepe exercitationem et nemo aspernaturnon porro hic repellendus adipisci aut praesentium sunt. Eum facilis galisum sed possimus autemUt quis et ducimus fugiat et possimus itaque At explicabo eveniet. Vel possimus consequaturEt commodi et sint reiciendis et commodi suscipit sed ipsum maxime. Ut iste enimEos Quis aut voluptatibus quasi et doloremque rerum. Vel debitis provident aut ipsum aliquidet dolorum aut possimus enim. </p><ul><li>Sit dolores laborum qui reiciendis eligendi sed inventore explicabo et unde quaerat! </li><li>Qui labore cumque et ipsa perspiciatis? </li><li>Sed odio aspernatur quo quia optio et dolores fuga. </li><li>A odit animi ut assumenda voluptatem et sunt quisquam! </li><li>33 culpa accusamus est vero itaque sed tenetur nisi? </li></ul>
        <p>Sit sint omnis ut amet commodised ratione et commodi velit. Et voluptas fuga qui nobis dignissimoset voluptates. Aut laboriosam suscipitEt consequatur qui veniam delectus et quos illo et eveniet adipisci. Eum ipsum similiqueIn delectus et soluta eaque ea omnis perferendis. Ad magni doloremque <em>Aut esse eos earum facilis qui dolor reprehenderit</em>. Aut incidunt ipsam sit inventore reiciendisNon quaerat et architecto deserunt vel placeat nulla et repudiandae iste. Ut sint voluptates et vitae magnam <strong>Est delectus aut magnam provident nam eius dolorum sit quasi galisum</strong>. </p>
        <p>Ut reiciendis sequi <em>Aut praesentium non aliquam distinctio et laboriosam quia</em> sed expedita pariatur qui eius aliquid et quod expedita. Ut assumenda debitis <strong>Ut deserunt aut cupiditate libero nam ipsum temporibus</strong>. Vel neque repellatVel velit rem delectus commodi. Sed voluptate nequeEos quibusdam cum nostrum iusto nam quam blanditiis. Eum impedit galisumUt placeat ab consequuntur quas et dolores autem eos perspiciatis autem ut impedit nihil et placeat delectus. Eum adipisci animi et totam nullaaut temporibus. Est dolores similiqueVel repellat ex rerum autem et galisum ipsum At officiis velit ea quia sint qui voluptas harum? </p>
        <p>Est fuga quaerat et explicabo sintNam similique sit aspernatur dignissimos ut accusamus nesciunt est rerum culpa et quia fugit. Ut eius laboreEt numquam sed vero praesentium? Est unde debitis <em>Ea esse qui eius sequi ex assumenda quaerat cum dolorem neque</em>. Eum recusandae undeId dolorum est fugit repellat sed maiores beatae est corporis ipsa qui quia ipsum a dolor nisi. Ut delectus tenetur et galisum deseruntUt ratione nam ipsam facere est ipsa internos eos odit ipsum sed tempore placeat. Eos eveniet molestiasQuo aliquam et tenetur voluptate aut voluptates voluptate est galisum soluta ex asperiores fuga. Aut autem blanditiis et enim facere <strong>Est galisum hic omnis reiciendis 33 voluptas obcaecati id illum facilis</strong> et quidem labore. </p>
        <p>Aut animi dicta est vero galisum <strong>At odio At quasi placeat</strong> id ullam magni qui odio quas et enim perferendis. Eum nihil commodiAut odit vel quia dolor? Et consequatur minima qui voluptatum laboreSed quam ut ullam animi hic laboriosam magnam. Est maiores culpa33 voluptatem sed officia cumque qui error architecto. Ea laudantium illo vel voluptatum iusto <em>Ut voluptatem vel quibusdam dolores</em>. </p>
        <p>Et quis dolor et omnis praesentiumest autem vel quidem internos? A consequatur iste ut odio quiaet minus et possimus explicabo ut nihil explicabo. Est eius ratione non inventore sintest nostrum. Aut odio fugiatEt laborum cum laborum dolorem in temporibus illum. Ut nostrum error id optio oditnam modi aut molestias praesentium qui doloremque architecto. Eum saepe nobis <strong>Sit voluptatem et ipsam placeat et voluptas quia</strong> et molestias modi qui accusantium iste. Qui ipsam reiciendisQui pariatur id consectetur dolor ut ipsum deserunt ex aperiam similique qui natus repellendus et nemo aspernatur? Est optio rerum qui voluptatem accusantiumet molestias. Et minima architectoEx consectetur sit accusamus inventore aut minus labore ad distinctio dolor et odit asperiores. </p>
        <p>Ea modi aspernaturEt cupiditate a quas unde eos recusandae laborum et autem beatae aut dolorem dicta ab galisum accusamus. Rem maxime illo eos eveniet magni <strong>Qui beatae 33 laudantium obcaecati</strong> et iusto suscipit ut odio exercitationem vel quibusdam sapiente. Aut enim obcaecati aut exercitationem nullaSed autem sed animi cupiditate sed ipsam quibusdam est aspernatur explicabo ut temporibus consequatur. Qui quia saepeSed neque sit dolores quam et reiciendis iusto non aliquam ipsa aut galisum maiores ex obcaecati aliquam. Id dolorum iustoAb reiciendis et illum accusamus est quas corporis ut rerum labore rem esse Quis. </p>
        <p>Aut voluptates quae est ipsam accusamussit dolor eos excepturi quasi. Et sequi eius et molestiae ducimusQui recusandae sit praesentium dolor. Ut natus voluptas et nesciunt doloremNam assumenda qui ipsa odio et galisum ullam est veritatis ullam. Ut aliquam saepe in error doloresAut natus qui dolores suscipit. 33 corrupti natusEum maiores quo enim ratione qui sint porro est voluptatem quos in facilis similique. Qui nulla nisi <strong>Ut dolor eum molestias eaque non nihil quam</strong>! Sit modi laboriosam <em>Non quia qui consequatur nostrum in magni voluptatem id reprehenderit nostrum</em> et quae autem sed eius quia. </p>
        <p>Aut obcaecati voluptas <em>Et iure qui recusandae expedita qui voluptatum sapiente</em> a expedita officiis nam voluptatem alias et placeat voluptates. In laboriosam ipsa At odit quiaUt sunt est quasi fuga hic quidem quia sed exercitationem consectetur 33 ipsum accusamus. Vel molestiae voluptatem sit blanditiis isteet cupiditate. Ut consequuntur ipsumNon iusto sit expedita enim et voluptas tempore vel fuga enim. Et totam ducimus qui nihil omnisAut repudiandae et animi omnis At illum accusamus et tempora odio. </p>
    </section>
{/block}